name: Verify Publish
description: Verify package version and get npm tag. Also get working directory if package lives under a monorepo
outputs:
  npm_tag:
    description: The npm tag to publish under
  working_directory:
    description: The directory that contains the package to be published
runs:
  using: node20
  main: dist/index.js