# This workflow will run our tests, generate an lcov code coverage file,
# and send that coverage to Coveralls 

name: Code Coverage

on:
  workflow_call:
    inputs:
      test_script:
        required: false
        type: string
        default: npx jest --coverage
    secrets:
      NPM_TOKEN:
        required: false
      caller_github_token:
        required: true

jobs:
  Coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: ls .github
      - run: ls .github/workflows
